Shop项目/web/myadmin/urls.py
from django.conf.urls import url
from . views import IndexViews,UsersViews,CatesViews,GoodsViews

urlpatterns = [
	# 后台主界面跳转
    url(r'^$',IndexViews.index,name="myadmin_index"),

    # 登录页
    url(r'^login/$',IndexViews.myadmin_login,name="myadmin_login"),
    # 登录处理
    url(r'^dologin/$',IndexViews.myadmin_dologin,name="myadmin_dologin"),
    # 验证码
    url(r'^verifycode/$',IndexViews.verifycode,name="myadmin_vcode"),
    # 退出
    url(r'^logout/$',IndexViews.myadmin_logout,name="myadmin_logout"),

    # 用户管理
    # 用户添加列表
    url(r'^user/add/$',UsersViews.user_add,name="myadmin_user_add"),
    # 用户列表数据添加
    url(r'^user/insert/$',UsersViews.user_insert,name="myadmin_user_insert"),
    # 用户列表数据
    url(r'^user/index/$',UsersViews.user_index,name="myadmin_user_index"),
    # 用户数据编辑
    url(r'^user/edit/$',UsersViews.user_edit,name="myadmin_user_edit"),
    # 用户状态设置
    url(r'^user/setstatus/$',UsersViews.user_set_status,name="myadmin_user_set_status"),


    # 分类管理
    # 商品分类添加
    url(r'^cate/add/$',CatesViews.cate_add,name="myadmin_cate_add"),
    # 商品分类列表
    url(r'^cate/index/$',CatesViews.cate_index,name="myadmin_cate_index"),
    # 商品分类删除
    url(r'^cate/del/$',CatesViews.cate_del,name="myadmin_cate_del"),
    # 商品分类删除
    url(r'^cate/edit/$',CatesViews.cate_edit,name="myadmin_cate_edit"),

    # 商品管理
    # 商品添加页
    url(r'^goods/add/$',GoodsViews.goods_add,name="myadmin_goods_add"),
    # 商品添加
    url(r'^goods/insert/$',GoodsViews.goods_insert,name="myadmin_goods_insert"),
    # 商品列表页
    url(r'^goods/index/$',GoodsViews.goods_index,name="myadmin_goods_index"),
    # 用户数据编辑
    url(r'^goods/edit/$',GoodsViews.goods_edit,name="myadmin_goods_edit"),


]

Shop项目/web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [

    # 富文本编辑器
    url(r'^ueditor/', include('ueditor.urls')),

    # 后台url
    url(r'^myadmin/', include('myadmin.urls')),
    
    # 前台url
    url(r'^shop/', include('shop.urls')),
    url(r'^', include('shop.urls')),

    # url(r'^admin/', admin.site.urls),

]

Shop项目/web/myadmin/models.py
from django.db import models

# Create your models here.


# 定义用户模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=77)
    # phone = models.CharField(max_length=11,unique=True)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = (
        (0, '女'),
        (1, '男'),
    )
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常  1禁用 
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)

# 商品模型
class Goods(models.Model):
    # id 所属分类，商品名，图片，添加时间，销量

    cateid = models.ForeignKey(to="Cates",to_field="id")
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField()
    ordernum = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    # 0新品，1热卖，2，推荐，下架
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 购物车模型
class Cart(models.Model):
    # id 用户uid 商品goodsid 数量num
    uid = models.ForeignKey(to="Users",to_field="id")
    goodsid = models.ForeignKey(to="Goods",to_field="id")
    num = models.IntegerField()

# 订单
class Order(models.Model):
    uid = models.ForeignKey(to="Users",to_field="id")
    username = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    totalprice = models.FloatField()
    # 0 未支付 1已支付 2已发货 3已收货 4以评价 5取消
    status = models.IntegerField(default=0)
    # 0支付宝 1.微信 3银联 4其它 4货到付款
    paytype = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    paytime = models.DateTimeField(null=True)

# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey(to="Order", to_field="id")
    goodsid = models.ForeignKey(to="Goods", to_field="id")
    num = models.IntegerField()

Shop项目/web/myadmin/views/CatesViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.core.urlresolvers import reverse

from .. models import Cates
# Create your views here.

# 封装函数。格式化获取分类数据
def get_cates_all():
	# 获取所有分类
	# data = Cates.objects.all()

	# 解析SQL语句排序
	data = Cates.objects.extra(select = {'paths':'concat(path,id)'}).order_by('paths')

	# 处理数据的顺序,缩进,及父级名
	for x in data:
		l = x.path.count(',')-1
		x.sub = l*'| '
		# 添加父级名字
		if x.pid == 0:
			x.pname = '顶级分类'
		else:
			x.pname = Cates.objects.get(id=x.pid).name

	return data

# 分类 列表
def cate_index(request):
	# 获取数据
	data = get_cates_all()

	# 分配数据
	context = {'catelist':data}
	# 加载模板
	return render(request,'myadmin/cates/index.html',context)

# 分类 添加
def cate_add(request):
	if request.method == 'POST':
		# 接收数据
		data = {}
		data['name'] = request.POST.get('name')
		data['pid'] = request.POST.get('pid')

		# 判断是否为顶级分类
		if data['pid'] == '0':
			data['path'] = '0,'
		else:
			# 获取当前父级的path路径
			pob = Cates.objects.get(id=data['pid'])
			# 拼接当前数据的path
			data['path'] = pob.path+data['pid']+','
		# 数据入库
		ob = Cates(**data)
		ob.save()

		return HttpResponse('<script>alert("添加成功");location.href="'+reverse('myadmin_cate_index')+'"</script>')
		
	else:
		# 显示表单

		# 获取当前已有的分类
		catelist = get_cates_all()
		# 分配数据
		context = {'catelist':catelist}
		# 加载一个模板
		return render(request,'myadmin/cates/add.html',context)

# 分类 删除
def cate_del(request):

	cid = request.GET.get('cid')
	print(cid)
	# 判断当前分类下是否还有子类
	res = Cates.objects.filter(pid=cid).count()
	if res:
		# 有子类
		return JsonResponse({'msg':'当前类下有子类,不能删除','code':1})

	# 判断当前分类下是否还有商品


	# 接受cid，获取对象
	ob = Cates.objects.get(id=cid)
	# 执行删除
	ob.delete()
	return JsonResponse({'msg':'删除成功','code':0})

# 分类 名字修改
def cate_edit(request):
	try:
		# 获取 参数
		cid = request.GET.get('cid')
		newname = request.GET.get('newname')

		# 获取对象
		ob = Cates.objects.get(id=cid)
		ob.name = newname
		# 修改属性
		ob.save()
		data = {'msg':'更新成功','code':0}
	except:
		data = {'msg':'更新失败','code':1}
	# 返回结果
	return JsonResponse(data)

Shop项目/web/myadmin/views/GoodsViews.py
from django.shortcuts import render
from django.http import HttpResponse
from . CatesViews import get_cates_all
from .. models import Cates,Goods
from . UsersViews import uploads_pic
import os
from web.settings import BASE_DIR
# Create your views here.

# 商品添加 表单
def goods_add(request):
    # 获取当前所有的分类数据
    data = get_cates_all()
    # 分配数据
    context = {'catelist':data}

    # 显示一个添加的表单
    return render(request,'myadmin/goods/add.html',context)

# 商品 添加操作
def goods_insert(request):
	try:
		# 接收表单数据
		data = request.POST.dict()
		data.pop('csrfmiddlewaretoken')

		sku_price = request.POST.getlist('sku_price')
		sku_stock = request.POST.getlist('sku_stock')

		# 处理分类对象
		data['cateid'] = Cates.objects.get(id=data['cateid'])

		# 判断是否有图片的上传
		myfile = request.FILES.get('pic',None)
		if not myfile:
			return HttpResponse('<script>alert("必须上传图片");history.back(-1)</script>')
		# 处理 上传的文件
		data['pic_url'] = uploads_pic(myfile)

		# 执行添加
		ob = Goods(**data)
		ob.save()
		return HttpResponse('<script>alert("商品添加成功");location.href="/myadmin/goods/index";</script>')

	except Exception as e:
		print('商品添加',e)

	return HttpResponse('<script>alert("商品添加成功");history.back(-1)</script>')

# 商品列表
def goods_index(request):
    # 获取所有的商品对象
    data = Goods.objects.all()
    # 导入分页类
    from django.core.paginator import Paginator
    # 实例化分页类(每页显示几条)
    p = Paginator(data,5)
    # 获取当前页的数据
    pageindex = request.GET.get('page',1)
    userlist = p.page(pageindex)
    # 分配数据
    context = {'goodslist':data,'userlist':userlist}
    # 加载模板
    return render(request,'myadmin/goods/index.html',context)

# 商品编辑
def goods_edit(request):

    # 接受商品id
    cateid = request.GET.get('goodsid')
    # 获取当前用户对象
    ob = Goods.objects.get(id = cateid)
    # 获取当前所有的分类数据
    data = get_cates_all()

    # 判断当前的请求方式
    if request.method == 'POST':
        # 判断所属分类是否更新
        if request.POST.get('cateid'):
            ob.cateid_id = request.POST.get('cateid')
        # 判断头像是否更新
        try:
            myfile = request.FILES.get('pic',None)
            if myfile:
                # 如果有新头像上传，则先删除原头像图片
                if ob.pic_url:
                    os.remove(BASE_DIR+ob.pic_url)
                # 再上传新的头像
                ob.pic_url = uploads_pic(myfile)
        except Exception as e:
            print('头像更新操作',e)

        # 更新其它字段
        try:
            ob.goodsname = request.POST.get('goodsname')
            ob.title = request.POST.get('title')
            ob.price = request.POST.get('price')
            ob.goodsnum = request.POST.get('goodsnum')
            if request.POST.get('goodsinfo'):
                ob.goodsinfo = request.POST.get('goodsinfo')
            ob.save()
        except Exception as e:
            print('字段更新操作',e)
        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/goods/index/";</script>')

    else:
        # 显示编辑表单
        context = {'uinfo':ob,'catelist':data}
        return render(request,'myadmin/goods/edit.html',context)

Shop项目/web/myadmin/views/IndexViews.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def index(request):
    
    return render(request,'myadmin/index.html')


# 登录页面
def myadmin_login(request):

	# 加载页面
	return render(request,'myadmin/login.html')

# 处理登录
def myadmin_dologin(request):
	# 检测验证码是否正确
	if request.session.get('verifycode').upper() != request.POST.get('vcode').upper():
		return HttpResponse('<script>alert("验证码错误");location.href="/myadmin/login"</script>')

	# 判断用户名是否存在，验证密码是否正确
	if request.POST['username'] == 'root' and request.POST['password']:
		# 成功，把用户信息记录在session中
		request.session['AdminUser'] = {'username':'root','uid':1}
		return HttpResponse('<script>alert("登录成功");location.href="/myadmin"</script>')

	# 返回信息
	return HttpResponse('<script>alert("账号或密码错误");location.href="/myadmin/login"</script>')

# 验证码
def verifycode(request):
    #引入绘图模块
    from PIL import Image, ImageDraw, ImageFont
    #引入随机函数模块
    import random
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), 255)
    width = 100
    height = 52
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象
    font = ImageFont.truetype('AGaramondPro-Regular.otf', 23)
    # font = ImageFont.truetype('FreeMono.ttf', 23)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((10, 18), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 18), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 18), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 18), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str

    #内存文件操作
    import io
    # from io import cStringIO
    # import cStringIO
    # buf = cStringIO.StringIO()
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

# 退出登录
def myadmin_logout(request):
	del request.session['AdminUser']

	return HttpResponse('<script>alert("退出成功");location.href="/myadmin/login"</script>')

Shop项目/web/myadmin/views/UsersViews.py
from django.shortcuts import render
from django.http import HttpResponse,JsonResponse

from django.contrib.auth.hashers import make_password, check_password
from .. models import Users
from web.settings import BASE_DIR
import os

# Create your views here.
# 用户模型的管理

# 用户列表
def user_index(request):
    try:
        # 获取所有用户数据
        data = Users.objects.all()

        # 获取搜索条件
        types = request.GET.get('types',None)
        keywords = request.GET.get('keywords',None)
        # 判断是否搜索
        if types == 'all':
            from django.db.models import Q
            data = data.filter(Q(id__contains=keywords)|Q(nikename__contains=keywords)|Q(email__contains=keywords)|Q(phone__contains=keywords))
        elif types :
            search = {types+'__contains':keywords}
            data = data.filter(**search)

        # 导入分页类
        from django.core.paginator import Paginator
        # 实例化分页类(每页显示几条)
        p = Paginator(data, 5)
        # 获取当前的页码数(第几页)
        pageindex = request.GET.get('page',1)
        # 获取当前页的数据
        userlist = p.page(pageindex)
        # 获取所有的页码
        # pages = p.page_range
        # pages = p.num_pages
        # 分配数据
        context = {'userlist':userlist}
        # 加载模板
        return render(request,'myadmin/users/index.html',context)
    except Exception as e:
        print('分页',e)
    
# 用户添加表单
def user_add(request):
    return render(request,'myadmin/users/add.html')

# 用户执行添加
def user_insert(request):
    # 接收表单数据
    data = request.POST.dict()
    data.pop('csrfmiddlewaretoken')

    # 处理密码 加密
    data['password'] = make_password(data['password'], None, 'pbkdf2_sha256')

    # 头像上传
    # 接收上传的文件
    myfile = request.FILES.get('pic',None)
    if not myfile:
        # 没有选择头像上传,
        return HttpResponse('<script>alert("没有选择头像上传");history.back(-1);</script>')

    # 处理头像的上传  1.jpg ==> [1,jpg]
    data['pic_url'] = uploads_pic(myfile)
    
    try:
        # 创建模型,添加数据
        ob = Users(**data)
        ob.save()
        # 跳转到列表页
        return HttpResponse('<script>alert("添加成功");location.href="/myadmin/user/index/";</script>')
    except:
        pass
    return HttpResponse('<script>alert("添加失败");history.back(-1);</script>')

# 头像上传的处理代码
def uploads_pic(myfile):
    try:
        import time
        # 时间+图片名
        filename = str(time.time())+"."+myfile.name.split('.').pop()
        # 图片上传的目录
        destination = open(BASE_DIR+"/static/uploads/"+filename,"wb+")
        for chunk in myfile.chunks():# 分块写入文件  
            destination.write(chunk)  
        destination.close()
        return '/static/uploads/'+filename
    except Exception as e:
        print('头像上传处理错误',e)
        return False

# 用户编辑
def user_edit(request):

    # 接受用户id
    uid = request.GET.get('uid')
    # 获取当前用户对象
    ob = Users.objects.get(id = uid)


    # 判断当前的请求方式
    if request.method == 'POST':
        # 判断密码是否更新
        if request.POST.get('password',None):
        # 更新密码
            ob.password = make_password(request.POST['password'], None, 'pbkdf2_sha256')
        
        # 判断头像是否更新
        try:
            myfile = request.FILES.get('pic',None)
            print(myfile)
            if myfile:
                # 如果有新头像上传，则先删除原头像图片
                if ob.pic_url:
                    os.remove(BASE_DIR+ob.pic_url)
                # 再上传新的头像
                ob.pic_url = uploads_pic(myfile)
        except Exception as e:
            print('头像更新操作',e)
        # 判断是否有传值
        if request.POST.get('age'):
            ob.age = request.POST.get('age')


        # 更新其它字段
        try:
            ob.nikename = request.POST.get('nikename',None)
            ob.email = request.POST.get('email',None)
            ob.phone = request.POST.get('phone',None)
            ob.sex = request.POST.get('sex',None)
            ob.save()
        except Exception as e:
            print('字段更新操作',e)
        return HttpResponse('<script>alert("更新成功");location.href="/myadmin/user/index/";</script>')

    else:
        # 显示编辑表单
        context = {'uinfo':ob}
        return render(request,'myadmin/users/edit.html',context)

# 用户状态跟新
def user_set_status(request):
    # 通过uid获取当前用户对象
    ob = Users.objects.get(id=request.GET.get('uid'))
    ob.status = request.GET.get('status')
    ob.save()
    return JsonResponse({'msg':'状态更新成功','code':0})

Shop项目/web/templates/myadmin/cates/add.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类添加</title>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title am-fl">
                        商品分类添加操作
                    </div>
                    <div class="widget-function am-fr">
                        <a href="javascript:;" class="am-icon-cog">
                        </a>
                    </div>
                </div>
                <div class="widget-body am-fr">
                    <form action="{% url 'myadmin_cate_add' %}" method="POST" enctype="multipart/form-data" class="am-form tpl-form-line-form">
                        {% csrf_token %}
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                所属分类
                            </label>
                            <select name="pid" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              <option value="0">顶级分类</option>
                              {% for v in catelist %}
                              <option value="{{ v.id }}" >{{ v.sub }}{{v.name}}</option>
                              {% endfor %}
                            </select>
                        </div>
                        <div class="am-form-group">
                            <label for="user-name" class="am-u-sm-3 am-form-label">
                                分类名称
                            </label>
                            <div class="am-u-sm-9">
                                <input type="text" name="name" class="tpl-form-input" 
                                 placeholder="分类名称">
                            </div>
                        </div>
                        
                        <div class="am-form-group">
                            <div class="am-u-sm-9 am-u-sm-push-3">
                                <button class="am-btn am-btn-primary tpl-btn-bg-color-success ">
                                    提交
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Shop项目/web/templates/myadmin/cates/index.html
{% extends 'myadmin/index.html' %}

{% block title %}
<title>后台商品分类列表</title>
{% endblock %}


{% block con %}
<div class="row-content am-cf">
    <div class="row">
        <div class="am-u-sm-12 am-u-md-12 am-u-lg-12">
            <div class="widget am-cf">
                <div class="widget-head am-cf">
                    <div class="widget-title  am-cf">商品分类列表</div>
                </div>
                <div class="widget-body  am-fr">

                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-6">
                        <div class="am-form-group">
                            <div class="am-btn-toolbar">
                                <div class="am-btn-group am-btn-group-xs">
                                    <a href="{% url 'myadmin_cate_add' %}" class="am-btn am-btn-default am-btn-success"><span class="am-icon-plus"></span> 新增</a>
                                    <!-- <button type="button" class="am-btn am-btn-default am-btn-secondary"><span class="am-icon-save"></span> 保存</button> -->
                                    <!-- <button type="button" class="am-btn am-btn-default am-btn-warning"><span class="am-icon-archive"></span> 审核</button> -->
                                    <!-- <button type="button" class="am-btn am-btn-default am-btn-danger"><span class="am-icon-trash-o"></span> 删除</button> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    <form> 
                    <div class="am-u-sm-12 am-u-md-6 am-u-lg-3">
                        <div class="am-form-group tpl-table-list-select">
                            <select name="types" data-am-selected="{btnSize: 'sm'}" style="display: none;">
                              <option value="all" {% if request.GET.types == 'all' %} selected {% endif %}>所有类别</option>
                              <!-- <option value="phone" {% if request.GET.types == 'phone' %} selected {% endif %}>手机号</option>
                              <option value="id" {% if request.GET.types == 'id' %} selected {% endif %}>ID</option>
                              <option value="nikename" {% if request.GET.types == 'nikename' %} selected {% endif %}>昵称</option>
                              <option value="email" {% if request.GET.types == 'email' %} selected {% endif %}>邮箱</option> -->
                            </select>
                        </div>
                    </div>
                    <div class="am-u-sm-12 am-u-md-12 am-u-lg-3">
                        <div class="am-input-group am-input-group-sm tpl-form-border-form cl-p">
                            <input type="text" name="keywords" value="{{request.GET.keywords}}" class="am-form-field ">
                            <span class="am-input-group-btn">
                                <button class="am-btn  am-btn-default am-btn-success tpl-table-list-field am-icon-search"></button>
                            </span>
                        </div>
                    </div>
                    </form>

                    <div class="am-u-sm-12">
                        <table width="100%" class="am-table am-table-compact am-table-striped tpl-table-black ">
                            <thead>
                                <!-- 商品分类列表字段 -->
                                <tr>
                                    <th>ID</th>
                                    <th>分类名</th>
                                    <th>所属父级</th>
                                    <th>该类下的商品数量</th>
                                    <th>Path路径</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                <!-- 商品分类列表数据显示 -->
                                {% for v in catelist %}
                                <tr >
                                    <td class="am-text-middle">{{v.id}}</td>
                                    <td class="am-text-middle cate_name">{{ v.sub }}<span cid="{{ v.id }}">{{v.name}}</span></td>
                                    <td class="am-text-middle">{{v.pname}}</td>
                                    <td class="am-text-middle">{{v.goods_set.count|default:'无'}}</td>
                                    <td class="am-text-middle">{{v.path}}</td>
                                    
                                    <!-- 商品分类列表编辑功能 -->
                                    <td class="am-text-middle">
                                        <div class="tpl-table-black-operation">
                                            <a href="javascript:void(0)" cid="{{ v.id }}" class="removeCate tpl-table-black-operation-del">
                                                <i class="am-icon-pencil"></i> 删除
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                                <!-- more data -->
                            </tbody>
                        </table>
                    </div>
                    <div class="am-u-lg-12 am-cf">

                        <div class="am-fr">
                            <ul class="am-pagination tpl-pagination">
                                <!-- <li class="am-disabled"><a href="#">«</a></li> -->
                                <!-- <li class="am-active"><a href="#">1</a></li>-->
                                
                                <!-- <li><a href="#">»</a></li> -->
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>

    // 分类编辑
        $('.cate_name').dblclick(function(){
            // 1.绑定双击事件,获取name换成input
            var span = $(this).find('span')
            // 获取当前分类名字
            var catename = span.text()
            // 创建一个input
            var inp = $('<input type="text" style="color:black" value="'+catename+'">')
            // 把分类名字换成input
            $(this).find('span').html(inp)
            // 让input中的值 处于选中状态
            inp.select()
            // 获取当前选择的元素的分类id
            var cid = span.attr('cid')

            // 2.给input绑定丧失焦点事件，判断是否更新了name,发送ajax去修改
            inp.blur(function(){
                // 获取当前新的name
                var newname = $(this).val()
                // 判断当前的值和原来的值是否一样
                if(newname == catename){
                    // 不需要修改,恢复原样
                    span.html(catename)
                }else{
                    // 需要发送ajax去更新
                    $.get('{% url 'myadmin_cate_edit' %}',{'cid':cid,'newname':newname},function(data){
                        // 判断是否更新成功
                        if(data['code'] == 0){
                            span.html(newname)
                            alert(data['msg'])
                        }
                    },'json')
                }
            })


        })
    // 删除按钮事件
    $('.removeCate').click(function(){
        // $(this) window 窗口对象->文档对象(DOM)->location(地址对象)->history(历史对象)

        // 获取当前选择的分类的id
        var cid = $(this).attr('cid')
        var a = $(this)
        // // 发送ajax请求，到后台执行删除
        $.get('{% url 'myadmin_cate_del' %}',{'cid':cid},function(data){
            // 判断当前的返回值
            if(data['code']==0){
                a.parents('tr').remove()
            }
            alert(data['msg'])
        },'json')
    })
</script>
{% endblock %}