Shop项目/web/web/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [

    # 富文本编辑器
    url(r'^ueditor/', include('ueditor.urls')),

    # 后台url
    url(r'^myadmin/', include('myadmin.urls')),
    
    # 前台url
    url(r'^shop/', include('shop.urls')),
    url(r'^', include('shop.urls')),

    # url(r'^admin/', admin.site.urls),

]

Shop项目/web/myadmin/models.py
from django.db import models

# Create your models here.


# 定义用户模型
class Users(models.Model):
    nikename = models.CharField(max_length=20,null=True)
    password = models.CharField(max_length=77)
    # phone = models.CharField(max_length=11,unique=True)
    phone = models.CharField(max_length=11)
    email = models.CharField(max_length=100)
    age = models.IntegerField(null=True)
    pic_url = models.CharField(max_length=100)
    SEX_CHOICES = (
        (0, '女'),
        (1, '男'),
    )
    sex = models.CharField(max_length=1,null=True,choices=SEX_CHOICES)
    # 0 正常  1禁用 
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 商品分类模型
class Cates(models.Model):
    name = models.CharField(max_length=20)
    pid = models.IntegerField()
    path = models.CharField(max_length=50)

# 商品模型
class Goods(models.Model):
    # id 所属分类，商品名，图片，添加时间，销量

    cateid = models.ForeignKey(to="Cates",to_field="id")
    goodsname = models.CharField(max_length=50)
    title = models.CharField(max_length=255)
    price = models.FloatField()
    goodsnum = models.IntegerField()
    pic_url = models.CharField(max_length=255)
    goodsinfo = models.TextField()
    ordernum = models.IntegerField(default=0)
    clicknum = models.IntegerField(default=0)
    # 0新品，1热卖，2，推荐，下架
    status = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)

# 购物车模型
class Cart(models.Model):
    # id 用户uid 商品goodsid 数量num
    uid = models.ForeignKey(to="Users",to_field="id")
    goodsid = models.ForeignKey(to="Goods",to_field="id")
    num = models.IntegerField()

# 订单
class Order(models.Model):
    uid = models.ForeignKey(to="Users",to_field="id")
    username = models.CharField(max_length=20)
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=255)
    totalprice = models.FloatField()
    # 0 未支付 1已支付 2已发货 3已收货 4以评价 5取消
    status = models.IntegerField(default=0)
    # 0支付宝 1.微信 3银联 4其它 4货到付款
    paytype = models.IntegerField(default=0)
    addtime = models.DateTimeField(auto_now_add=True)
    paytime = models.DateTimeField(null=True)

# 订单详情
class OrderInfo(models.Model):
    orderid = models.ForeignKey(to="Order", to_field="id")
    goodsid = models.ForeignKey(to="Goods", to_field="id")
    num = models.IntegerField()

Shop项目/web/shop/views/MemberViews.py
############### 用户模块 ###############
from django.contrib.auth.hashers import make_password, check_password
from django.http import HttpResponse,JsonResponse,Http404
from PIL import Image, ImageDraw, ImageFont
from django.shortcuts import render
from myadmin.models import Users
import random
import os
import io

# ==================== 登录 ====================

# 显示登录页面
def shop_login(request):

	return render(request,'myhome/member/login.html')

# 执行登录
def shop_dologin(request):
	try:
		# 验证手机号码，判断用户是否存在
		ob = Users.objects.get(phone=request.POST['phone'])
		# 验证密码
		pw = check_password(request.POST['password'],ob.password)
		# 验证验证码
		vc = request.POST['code']
		# print(vc)
		if vc.upper() != request.session['verifycode']:
			return HttpResponse('<script>alert("验证码有误");history.back(-1);</script>')
		if pw:
			# 验证成功
			request.session['vipUser'] = {
			'id':ob.id,'phone':ob.phone,'password':ob.password,'pic_url':ob.pic_url,'nikename':ob.nikename
			}
			return HttpResponse('<script>alert("登录成功");location.href="/shop"</script>')
	except Exception as e:
		print('账号密码验证',e)

	return HttpResponse('<script>alert("手机号或密码不正确");history.back(-1);</script>')

# 退出登录
def shop_logout(request):
	del request.session['vipUser']
	return HttpResponse('<script>alert("退出成功");location.href="/shop"</script>')

# ==================== 注册 ====================

# 显示注册页面
def shop_register(request):

	return render(request,'myhome/member/register.html')

# 执行注册
def shop_doregister(request):
	try:
		# 接收表单数据
		data = request.POST.dict()
		print(data)
		# 暂时不存
		data.pop('csrfmiddlewaretoken')
		pwd2 = data.pop('password_confirm')
		data.pop('agree')

		# 验证手机短信验证码是否正确
		if data['vcode'] != request.session['msgcode']:
			return HttpResponse('<script>alert("手机验证码错误");history.back(-1)</script>')
		# 删除表单中的 vcode
		data.pop('vcode')

		# 判断是否为空
		if data['nikename'] == '' or data['phone'] == '' or data['password'] == '':
			return HttpResponse('<script>alert("请正确填写信息");history.back(-1)</script>')
		# 判断密码是否一致
		if data['password'] != pwd2:
			data['nikename'] == ''
			data['phone'] == ''
			return HttpResponse('<script>alert("密码不一致");history.back(-1)</script>')
		# 验证手机号是否存在
		res = Users.objects.filter(phone=data['phone']).count()
		if res:
			# 手机号已经存在
			return HttpResponse('<script>alert("手机号已存在");history.back(-1)</script>')

		# 密码进行加密处理
		data['password'] = make_password(data['password'], None, 'pbkdf2_sha256')
		

		# 执行注册  数据的添加
		obj = Users(**data)
		obj.save()
		return HttpResponse('<script>alert("注册成功，请登录");location.href="/shop/login/"</script>')

	except Exception as e:
		print('执行注册',e)

	return HttpResponse('<script>alert("注册失败，请联系管理员");location.href="/shop/register/"</script>')

# ==================== 验证 ====================

# 验证码
def shop_code(request):
    
    #定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 40
    #创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    #创建画笔对象
    draw = ImageDraw.Draw(im)
    #调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    #定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ'
    #随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    #构造字体对象
    font = ImageFont.truetype('Inkfree.ttf', 23)
    #构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    #绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    #释放画笔
    del draw
    #存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    #内存文件操作
    
    buf = io.BytesIO()
    #将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    #将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

# 短信验证
def shop_sendMsg(request):
	import random
	# 接收手机号码
	phone = request.GET.get('phone')
	print(phone)
	# 随机验证码
	code = str(random.randint(10000,99999))
	# 把验证码存入session
	request.session['msgcode'] = code
	# 调用方法,发送短信验证
	res = hywx_send(phone,code)
	return JsonResponse(res)

# 短信接口
def hywx_send(mobile,code):
	#接口类型：互亿无线触发短信接口，支持发送验证码短信、订单通知短信等。
    #账户注册：请通过该地址开通账户http://user.ihuyi.com/register.html
    #注意事项：
    #（1）调试期间，请用默认的模板进行测试，默认模板详见接口文档；
    #（2）请使用 用户名 及 APIkey来调用接口，APIkey在会员中心可以获取；
    #（3）该代码仅供接入互亿无线短信接口参考使用，客户可根据实际需要自行编写；
      
    # import urllib2
    import urllib
    import urllib.request
    import json
 
    #用户名 查看用户名请登录用户中心->验证码、通知短信->帐户及签名设置->APIID
    account  = "C46788523" 
    #密码 查看密码请登录用户中心->验证码、通知短信->帐户及签名设置->APIKEY
    password = "0b838daf6a961f9c568c1cad56c3ab98"
    # mobile = request.GET.get('phone')
  
    text = "您的验证码是："+code+"。请不要把验证码泄露给其他人。"
    data = {'account': account, 'password' : password, 'content': text, 'mobile':mobile,'format':'json' }
    # req = urllib.request.urlopen(
    #     url= 'http://106.ihuyi.com/webservice/sms.php?method=Submit',
    #     data= urllib.parse.urlencode(data).encode('utf-8')
    # )
    # 获取接口响应的内容
    # content = req.read()
    # res = json.loads(content.decode('utf-8'))
    # 15637004571738806283

    res = {'code':2,'msg':'提交成功','id':'15637004571738806283','yzm':code}
    return res

Shop项目/web/shop/views/OrderViews.py
############### 其他模块 ###############
from django.shortcuts import render
from django.http import HttpResponse,Http404,JsonResponse

# 精选品牌
def shop_SelectedBrands(request):
	return render(request,'myhome/order/SelectedBrands.html')
	

# 全球购
def shop_GlobalPurchase(request):
	return render(request,'myhome/order/GlobalPurchase.html')

# 品牌馆
def shop_BrandPavilion(request):
	return render(request,'myhome/order/BrandPavilion.html')
	

Shop项目/web/templates/myhome/member/login.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>登录</title>
		<link rel="stylesheet" type="text/css" href="/static/myhome/css/login.css"/>
	</head>
	<body>
		<div id="append"></div>
		<div class="full_sc">
			<div class="head_cent head_cwo ClearFix">
				<div class="h_logo">
					<a href="{% url 'shop_homepage' %}">
						<img src="/static/myhome/image/logo.jpg"/>
					</a>
				</div>
				<div class="h_right">
					<img src="/static/myhome/image/top_center.jpg"/>
				</div>
			</div>
		</div>
		<div class="w980 ClearFix">
			<div class="logo_box ClearFix">
				<div class="login_b_l ClearFix">
					<a href="" title="日光生活">
						<img style="width: 560px;height: 360px;" src="/static/myhome/image/logo_img.jpg" alt="日光生活"/>
					</a>
				</div>
				<div class="login_b_r ClearFix">
					<div class="loginul ClearFix">
						<div class="login_h2 ClearFix">
							<h2>登录</h2>
							<div class="lognrtop">
								还没有账号-><a href="{% url 'shop_register' %}">快速注册</a>
							</div>
						</div>
						<div class="co">
							<div class="from">
								<form id="mainForm" action="{% url 'shop_dologin' %}" method="POST">
									{% csrf_token %}
									<div class="item">
									<input class="itxt" name="phone" placeholder="请输入登录账号" value="" >
									    <div class="err_box">
                                            <!-- <div class="err_msg2" style="display: none;">登录名可能是您的手机号、邮箱或用户名 -->
                                            </div>
                                        </div>
									</div>
									<div class="item">
                                        <input class="itxt" placeholder="请输入密码" name="password" id="password" type="password">
                                        <div class="err_box">
                                            <!-- <div class="err_msg2" style="display: none;">您的密码可能为字母、数字或符号的组合</div> -->
                                        </div>
									</div>
									<div class="item item3">
		                                <input placeholder="验证码" autocomplete="off" tabindex="6" maxlength="4" size="10" class="itxt itxt_yzm" name="code" id="code" type="text" style="position: relative;width: 180px">
		                                <img id='verifycode' src="{% url 'shop_code' %}" alt="shop_code" style="position: absolute;right:20px" onclick="this.src='{% url 'shop_code' %}'+'?'+Math.random()"/>
		                                <!-- <div class="err_box">
		                                    <div class="err_msg2" style="display: none;" id="error_captcha">请输入右侧验证码</div>
		                                </div> -->
		                            </div>
		                            <div class="item item4">
										<div class="safe ClearFix">
                                            <span>
                                            <input tabindex="4" class="jdcheckbox" name="autoLogin" id="autoLogin" checked="checked" type="checkbox">
                                            <label for="autoLogin">记住用户名</label>
                                            </span>
                                            <span class="forget-pw-safe">
                                                <a target="_blank" class="" href="">忘记密码？</a>
                                            </span>
										</div>
									</div>
									<!-- 登录按钮 -->
									<div class="item">
										<div class="login-btn">
										<button><a tabindex="6" id="loginsubmit" class="btn-img btn-entry">立即登录</a></button>
                                       </div>
									</div>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

Shop项目/web/templates/myhome/member/order.html
{% extends 'myhome/muban/muban.html' %}

{% block title %}
<title>个人订单</title>
{% endblock %}

{% block css%}
<link rel="stylesheet" type="text/css" href="/static/myhome/css/suercenter.css" />
{% endblock %}

{% block con %}
<!-- 内容区域 -->
<div class="w1000 ClearFix margin_top20">
	<!--左侧导航-->
	<div class="ur_left">
		<div class="ur_slide">
			<a href="{% url 'shop_homepage' %}"><h2 class="slide_h2"><b></b>我的快乐购</h2></a>
			<ul class="slide_list">
				<li class="no">
					<a href="">我的订单</a>
				</li>
				<li>
					<a href="">申请退款</a>
				</li>
				<li>
					<a href="">我的收藏</a>
				</li>
				<li>
					<a href="">我的优惠卷</a>
				</li>
				<li>
					<a href="">我的积分</a>
				</li>
			</ul>
		</div>
		<div class="ur_slide">
			<a href="{% url 'shop_homepage' %}"><h2 class="slide_h2"><b></b>我的快乐购</h2></a>
			<ul class="slide_list">
				<li class="no">
					<a href="">个人资料</a>
				</li>
				<li>
					<a href="">账号安全</a>
				</li>
				<li>
					<a href="">地址管理</a>
				</li>
			</ul>
		</div>
	</div>
	<!--左侧导航 E-->
	<div class="ur_right">
		<!--uer_top-->
		<div class="ur_location">
			<a href="">我的快乐购</a>
			<span>&gt;</span>
			<a class="a_cur" href="{% url 'shop_center_order' %}">我的订单</a>
		</div>
		<!--uer_top-->
		<div class="ur_r_list">
			<!-- 订单选项 -->
			<div class="ur_list_tab">
				<ul class="ur_tab_ul">
					<li class="on ">
						<a href="">全部订单</a>
					</li>
					<li>
						<a href="">待付款</a>
					</li>
					<li>
						<a href="">待发货</a>
					</li>
					<li>
						<a href="">待评价</a>
					</li>
				</ul>
				<div class="more_rk">
					<a href="" class="more_order">查看历史订单</a>
					<a href="" class="more_qqg_order">查看全球购订单&gt;&gt;</a>
				</div>
			</div>
			<!-- 订单选项 E-->
			<table class="order_table">
				<!-- 订单表头 -->
				<thead class="thead">
					<tr>
						<td class="padding_40">
							<div class="select_div">
								<div class="select_h2">
									<span>近三月的订单</span>
									<b></b>
								</div>
								<div class="select_list">
									<ul>
										<li data-name="近三月的订单" class="cur">
											<a href=""><b></b>近三月的订单</a>
										</li>
										<li data-name="近半年的订单" class="">
											<a href=""><b></b>半年的订单</a>
										</li>
										<li data-name="最近一年的订单" class="">
											<a href=""><b></b>最近一年的订单</a>
										</li>
									</ul>
								</div>
							</div>
						</td>
						<td>订单金额</td>
						<td>交易状态</td>
						<td>交易操作</td>
					</tr>
				</thead>
				<!-- 订单表头 E -->
				<tbody>
					<!--单号 时间-->
					{% for v in orderdata %}
					<tr class="tr_top">
						<td colspan="6">
							<span class="number">订单号：<a target="_blank" href="">{{ v.id }}</a></span>
							<span class="dealtime" title="下单时间">下单时间：{{ v.addtime|date:'Y-m-d H:i:s' }}</span>
						</td>
					</tr>
					<!--单号 时间 E-->
					<!--订单商品-->
					{% for vv in v.orderinfo_set.all %}
					<tr class="tr_bd">
						<td class="goods-item">
							<div class="p-img">
								<a href="{% url 'shop_info' %}?goodsid={{ vv.goodsid.id }}" target="_blank">
									<img class="" src="{{ vv.goodsid.pic_url }}" title="" height="60" width="60">
								</a>
							</div>
							<div class="p-msg">
								<div class="p-name">
									<a href="" class="a-link" target="_blank" title="">{{ vv.goodsid.goodsname }}</a>
								</div>
							</div>
						</td>
						<td>
							<div class="goods_price">￥{{ vv.goodsid.price }}</div>
						</td>
						<td>
							<div class="goods-number">x{{ vv.num }}</div>
						</td>
						<td rowspan="1">
							<div class="amount"><span>￥{% widthratio vv.goodsid.price 1 vv.num %}</span><br>（免运费）<br>在线支付</div>
						</td>
						<td rowspan="1">
							<div class="status">
								<span class="order-status">
									<span style="color:#999">
										{% if v.status == 0 %}
											未支付
										{% elif v.status == 1 %}
											以支付
										{% elif v.status == 2 %}
											2已发货
										{% elif v.status == 3 %}
											3已收货
										{% elif v.status == 4 %}
											4以评价
										{% elif v.status == 5 %}
											5取消
										{% endif %}
									</span>
								</span><br>
								<a href="" target="_blank">订单详情</a>
							</div>
						</td>
						<td rowspan="1">
							<div class="operate">
								<p><a href="javascript:void(0);" class="btn-del"><i class="icon-trash"></i>删除</a></p>
							</div>
						</td>
					</tr>
					{% endfor %}
					<!--订单商品 E-->
					{% endfor %}
				</tbody>
			</table>
		</div>
		<!--page-->
		<!--分页-->
		<div class="page_list margin_top20">
			<div class="page_r">
				<ul>
					<li class="pre a_btn un">
						<span><b><</b>上一页</span>
					</li>
					<li class="a_p_num">
						<span>1</span>
					</li>
					<li>
						<a href=""><span>2</span></a>
					</li>
					<li class="next a_btn">
						<a href=""><span>下一页<b>></b></span></a>
					</li>
			</div>
		</div>
		<!--分页end-->
		<!--pageend-->
	</div>
</div>
{% endblock %}

Shop项目/web/templates/myhome/member/register.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>注册</title>
		<link rel="stylesheet" type="text/css" href="/static/myhome/css/login.css"/>
        <script src="/static/myhome/js/jquery-1.8.3.min.js"></script>
	</head>
	<body>
		<div id="append"></div>
		<div class="full_sc">
			<div class="head_cent head_cwo ClearFix">
				<div class="h_logo">
					<a href="{% url 'shop_homepage' %}">
						<img src="/static/myhome/image/logo.jpg"/>
					</a>
				</div>
				<div class="h_right">
					<img src="/static/myhome/image/top_center.jpg"/>
				</div>
			</div>
		</div>
		<div class="w980 ClearFix">
			<div class="logo_box ClearFix">
				<div class="login_b_l ClearFix">
					<a href="" title="出发">
						<img src="/static/myhome/image/register.jpg" alt="出发"/>
					</a>
				</div>
				<div class="login_b_r ClearFix">
					<div class="loginul ClearFix">
					    <div class="login_h2 ClearFix">
						    <h2>用户注册</h2>
						    <div class="lognrtop">
								已有账号<a href="{% url 'shop_login' %}">在此登录</a>
							</div>
						</div>
                        <div class="form">
                        <form id="register_form" method="POST" action="{% url 'shop_doregister' %}">
                            {% csrf_token %}
                            <!-- 账号 -->
                            <div class="item">
                                <input placeholder="请输入昵称" class="itxt" name="nikename" id="name" type="text">
                            </div>
                            <!-- 手机号 -->
                            <div class="item">
                                <!-- <div class="err_box"></div> -->
                                <input placeholder="请输入手机号码" class="itxt"  name="phone" id="phone" type="text">
                                <!-- <div class="err_box"></div> -->
                            </div>
                            <!-- 验证码 -->
                            <div class="item items">
                                <input placeholder="验证码"  class="itxt itxt_yzm onfocustxt" name="vcode" id="mobile_code" type="text">
                                <!-- <a href="" class="ncm-btn ml5" tabindex="2" id="msg-input"> -->
                                    <button  type="button" class="SendMsg" style="background-color:#f6f6f6;width:135px;height:39px;border:1px solid #c8c8c8">获取短信验证码</button>
                            	<!-- </a> -->
                            </div>
                            <!-- 验证码 end-->
                            <!-- 密码框 -->
                            <div class="item item2">
                                <input placeholder="请输入密码(6位数)"   class="itxt" name="password" id="password" type="password">
                            </div>
                            <div class="item item2" id="pwddiv">
                                <input placeholder="请再次输入密码" class="itxt"  name="password_confirm" id="password_confirm" type="password">
                            </div>
                            <!-- 密码框end -->
                            <div class="item item5">
                                <div class="login-btn">
                                    <a id="loginsubmit" tabindex="7" class="btn-img btn-entry" href="javascript:document:register_form.submit();">立即注册</a>
                                </div>
                                <div class="agree">
                                    <input class="jdcheckbox" tabindex="8" name="agree" id="agree" checked="checked" type="checkbox">
                                    <label for="autoLogin">注册即表示同意<span><a href="" target="_blank">《用户服务协议》</a></span>条款</label>
                                </div>
                            </div>
                        </form>
                        </div>
					</div>
				</div>
			</div>
		</div>
        <script>
            // 短信验证码
            $('.SendMsg').click(function(){
                // 获取手机号
                var phone = $('#phone').val()
                // 验证手机号是否正确
                reg = /^\d{11}$/
                if(reg.test(phone)){
                    // 设置按钮不可点击,倒计时

                    // 发送短信验证码
                    $.get('{% url 'shop_sendMsg' %}',{'phone':phone},function(data){
                        console.log(data)
                    },'json')
                }
            })

            // 判断两次密码是否一致
            $('#password').change(function(){
                var a1 = this.value
                if(a1.length < 6){
                    alert('请填写6位数密码')
                }
                // $('#password_confirm').mouseout(function(){
                //     if(a1 != $(this).val()){
                //         alert("密码不一致");
                //     }
                // })
            })
            // 判断手机号
            $('#phone').change(function(){
                var check_phone = this.value
                if(check_phone.length != 11){
                    alert('手机号不正确')
                }
            })
        </script>
	</body>
</html>